# Code generated by runtimeconditions-binding-emitter 0.1.0 from model 596ad51ab247abcdfe96ba8b81ea6072f0ee61c9da5920e591f99edff6e23cf4; DO NOT EDIT.
from __future__ import annotations

from .bindings import (
    CommandLimit,
)

__all__ = [
    "CommandLimit",
]

raise RuntimeError('release smoke binding must not execute')
