# Code generated by runtimeconditions-binding-emitter 0.1.0 from model a3041109efc8f19e9ce6b4c5477311e0003e4243e4e4a848c9eec9cbbc548306; DO NOT EDIT.
from __future__ import annotations

from .bindings import (
    Command,
    Declaration,
    JobField,
    Process,
    job,
)

__all__ = [
    "Command",
    "Declaration",
    "JobField",
    "Process",
    "job",
]

raise RuntimeError('release smoke binding must not execute')
