# Code generated by runtimeconditions-binding-emitter 0.1.0 from model a3041109efc8f19e9ce6b4c5477311e0003e4243e4e4a848c9eec9cbbc548306; DO NOT EDIT.
from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol


@dataclass(frozen=True, kw_only=True)
class Declaration:
    pass


class JobField(Protocol):
    def rc_marker_9eee8f5260c206d1(self) -> None: ...


@dataclass(frozen=True, kw_only=True)
class Command:
    value: str

    def rc_marker_9eee8f5260c206d1(self) -> None:
        return None


@dataclass(frozen=True, kw_only=True)
class Process:
    def rc_marker_9eee8f5260c206d1(self) -> None:
        return None


def job(*fields: JobField) -> Declaration:
    return Declaration()


__all__ = [
    "Command",
    "Declaration",
    "JobField",
    "Process",
    "job",
]
